cardio_report_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Medical Exam Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f9f9f9;
            color: #333;
        }
        .report-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: #fff;
            border: 1px solid #ccc;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 24px;
            color: rgb(51, 143, 131);
            margin: 0;
        }
        .header p {
            font-size: 14px;
            color: #000000;
        }
        .section-title {
            font-size: 18px;
            color: rgb(51, 143, 131);
            border-bottom: 2px solid rgb(51, 143, 131);
            padding-bottom: 5px;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        .attribute {
            margin: 10px 0;
            display: flex;
            justify-content: space-between;
        }
        .attribute span {
            font-weight: bold;
        }
        .summary {
            margin-top: 20px;
            padding: 15px;
            background-color: #f1f1f1;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .summary h2 {
            margin: 0 0 10px 0;
            font-size: 16px;
            color: #444;
        }
    </style>
</head>
<body>
    <div class="report-container">
        <div class="header">
            <h1>Medical Exam Report</h1>
            <p>Generated by CardioSense Health System</p>
        </div>
        <div class="section">
            <div class="section-title">Exam</div>
            <div class="attribute"><span>Exam Id:</span> {{ id }}</div>
        </div>
        <div class="section">
            <div class="section-title">Patient Information</div>
            <div class="attribute"><span>Age:</span> {{ age }}</div>
            <div class="attribute"><span>Sex:</span> {{ sex_decoded }}</div>
        </div>
        <div class="section">
            <div class="section-title">Medical Exam Details</div>
            <div class="attribute">
                <span>Chest Pain Type:</span> {{ chest_pain_type_decoded }}
            </div>
            <div class="attribute">
                <span>Resting Blood Pressure:</span> {{ resting_bp }} mmHg
            </div>
            <div class="attribute">
                <span>Cholesterol:</span> {{ cholesterol }} mg/dl
            </div>
            <div class="attribute">
                <span>Fasting Blood Sugar:</span> {{ fasting_bs_decoded }}  mg/dl
            </div>
            <div class="attribute">
                <span>Resting ECG:</span> {{ resting_ecg_decoded }}
            </div>
            <div class="attribute">
                <span>Max Heart Rate:</span> {{ max_hr }}
            </div>
            <div class="attribute">
                <span>Exercise Angina:</span> {{ exercise_angina_decoded }}
            </div>
            <div class="attribute">
                <span>Oldpeak (ST):</span> {{ oldpeak }}
            </div>
            <div class="attribute">
                <span>ST Slope:</span> {{ st_slope }}
            </div>
        </div>
        <div class="summary">
            <h2>Summary</h2>
            <p>{{ summary }}</p>
        </div>
    </div>
</body>
</html>
"""

llm_summary_template = """
### INSTRUCTION:
Your job is to generate a summary (DO NOT EXCEED 200 words) (NO PREAMBLE).
Based on the cardio exam content, Include in the summary text:
- The patient overall cardio health;
- Any health risks the patient may run into;
- If there is risk of developing cardiac disease, suggest medical specialties
to the patient;

Here is the cardio exam data dictionary:

Id: id of the exam
Age: age of the patient [years]
Sex: sex of the patient [M: Male, F: Female]
ChestPainType: chest pain type [TA: Typical Angina,
ATA: Atypical Angina, NAP: Non-Anginal Pain,ASY: Asymptomatic]
RestingBP: resting blood pressure [mm Hg]
Cholesterol: serum cholesterol [mm/dl]
FastingBS: fasting blood sugar [1: if FastingBS > 120 mg/dl, 0: otherwise]
RestingECG: resting electrocardiogram results [Normal: Normal,
 ST: having ST-T wave abnormality (T wave inversions and/or ST elevation or
 depression of > 0.05 mV), LVH: showing probable or definite
left ventricular hypertrophy by Estes' criteria]
MaxHR: maximum heart rate achieved [Numeric value between 60 and 202]
ExerciseAngina: exercise-induced angina [Y: Yes, N: No]
Oldpeak: oldpeak = ST [Numeric value measured in depression]
ST_Slope: the slope of the peak exercise ST segment [Up: upsloping,
Flat: flat, Down: downsloping]

### CARDIO EXAM CONTENT:
{exam}
"""
